DROP DATABASE IF EXISTS php_user;
CREATE DATABASE IF NOT EXISTS php_user;
USE php_user;
DROP TABLE IF EXISTS guestbook;
CREATE TABLE IF NOT EXISTS guestbook (
	id INT(5) NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL,
	password VARCHAR(32) NOT NULL,
	sex VARCHAR(16) NOT NULL,
	time  DATE NOT NULL,
	PRIMARY KEY (id)
);
DROP TABLE IF EXISTS content;
CREATE TABLE IF NOT EXISTS content (
	id INT(5) NOT NULL AUTO_INCREMENT,
	title VARCHAR(32) NOT NULL,
	content VARCHAR(32) NOT NULL,
	name VARCHAR(16) NOT NULL,
	time DATETIME NOT NULL ,
	type VARCHAR(16) NOT NULL,
	PRIMARY KEY (id)
);